### PR TITLE
Make {player,bullet}_size configurable through command-line arguments

### PR DESCRIPTION
**Pull request by nabijaczleweli**

### CODE REVIEW

**Comment by thecoshman** [comment]
Out of scope :-1:

Besides, there is no point starting to put everything configurable through CLI args. There's going to be stupid amounts of properties we would want 'settable', and that should be done via a (JSON) property file.

**Comment by nabijaczleweli** [comment]
More like YAML property file.

**Comment by thecoshman** [comment]
Bikeshed is that way :arrow_left:

**Comment by TheCatPlusPlus** [comment]
lol yaml

**Comment by thecoshman** [comment]
¬_¬ who changed where the bikeshed is? Stupid shithub letting people edit other peoples comments

**Comment by TheCatPlusPlus** [comment]
Anyway this is inconsistent. If you're going with configurable params then all of them should be configurable, this skips speeds.

Also player_size is not a radius, it's a side length.

**Comment by nabijaczleweli** [comment]
Players are circles, as @thecoshman w/ @Lalaland agreed

**Pull request closed without merging**
