### PR TITLE
Use a proper command-line parsing library

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Depend on `clap` v2.2

Modify `listen()` to take port as `u16`, as @Lalaland's branch does so (and it's the only logical option)

---

This change is [Reviewable](https://reviewable.io/reviews/loungecpp/tatsoryk/22)

### CODE REVIEW

**Comment by EthanSteinberg** [comment]
It doesn't really seem worth adding, but sure.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/loungecpp/tatsoryk/22#-:-KE8U0cv7d84Dfj4czT_:1630592404)_

**Comment by nabijaczleweli** [comment]
It's better than what we currently have, produces nice help strings, verifies arguments and is extensible.

**Comment by EthanSteinberg** [comment]
:+1:

**Comment by TheCatPlusPlus** [comment]
:+1: but I hope you realise this will never be used for anything beyond those two arguments.

Also all that authors crap can be skipped, we won't be shipping this anywhere anyway.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/loungecpp/tatsoryk/22#-:-KEAlI-K6EQK-s1kedxm:1358607396)_

**Pull request merged**
